# Spawning DMZs
# Use mob names (all uppercase) found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# "factor" is the relative rate of spawns (double between 0-1).
# A factor of "0" turns off spawning altogether. A factor of "0.3" means spawns will be reduced to 30% of standard rates.
#
# If you're unsure about level names, check "available-levels.txt" for a current list of levels.

GIANT:
  0:
    level: world_nether
    factor: 0
    x1: -10
    y1: 20
    z1: -20
    x2: -30
    y2: 60
    z2: 20


#-----------------------------------------------
# Prevent Portal Spawns

disable_portal_spawns: false

# If portal spawns are disabled (to mitigate weird spawning issues with other mobs), use this option to re-enable zombified piglin portal spawning if you wish.
allow_ziglin_portal_spawns: false


#-----------------------------------------------
# Prevent Mob Griefing
# Ender Dragon, Enderman, Creeper, Ghast, and Wither griefing can be global or area-restricted. The global option will override any blocked areas.
# Note: For Creeper, Ghast, and Wither, this is based on where the explosion happens. If the explosion happens just outside of the zone, blocks inside of the zone can still break. Plan accordingly.
# Like spawning DMZs, you can have a "factor". I don't know why you'd want to, but you can. Set it to zero or leave it blank to disable 100% of explosions.

prevent_dragon_grief:
  enabled: false
  global: true
  blocked-areas:
    0:

prevent_enderman_grief:
  enabled: false
  global: true
  blocked-areas:
    0:

prevent_creeper_grief:
  enabled: false
  global: false
  blocked-areas:
    0:
      level: world
      x1: -10
      y1: 20
      z1: -20
      x2: -30
      y2: 60
      z2: 20

prevent_ghast_grief:
  enabled: false
  global: true
  blocked-areas:
    0:

prevent_wither_grief:
  enabled: false
  global: true
  blocked-areas:
    0: